dotnet/arcade-pool-provider

job-to-helix-info.ps1

- Require params
- Reject non dev.azure.com urls

Fix usability issues

---

src/wwwroot/startupscripts/startagent-win.cmd

Kill VS and build-related processes which might prevent workspace cleanup

---

src/wwwroot/startupscripts/startagent-win.cmd

@mmitche was right, despite me not reproing it locally.

Abandoning variables inside IF blocks, moved to a GOTO implemention

---

src/wwwroot/startupscripts/startagent-win.cmd

Addresses https://github.com/dotnet/core-eng/issues/7698 - should prevent mystery leftover processes from affecting builds

Reboot machine after work if non-default workspace path gets used

---

src/ValidateModelStateAttribute.cs

We are getting a lot of "400 Bad Request" responses on this server
but the logs don't show why. This filter appears to be the culprit, so
add logging to test that hypothesis

Try adding some logging to track down 400 responses

---

src/HelixJobCreator.cs

(left in config as this might come back later).  Some logging tweaks to ensure timing measurement

Remove usage of storage account connection string 

---

NuGet.config
eng/Version.Details.xml
eng/Versions.props
src/Config.cs
src/Controllers/PoolProviderController.cs
src/HelixJobCreator.cs

Now just uses CancellationToken from ASP.NET and an updated library.

Address TCP connection starvation and allow job cancellation 

---

src/appsettings.dncenginternal-int.json
src/appsettings.dncenginternal-prod.json
src/appsettings.dncengpublic-int.json
src/appsettings.dncengpublic-prod.json

Also removed FreeBSD as that isn't coming together any time soon.

Add new queues so they can be tested prior to rollout.

---

eng/Version.Details.xml
eng/Versions.props
eng/common/templates/post-build/channels/generic-internal-channel.yml
eng/common/templates/post-build/channels/generic-public-channel.yml
eng/common/templates/steps/publish-logs.yml
eng/common/tools.ps1
eng/common/tools.sh
global.json
src/Microsoft.DotNet.HelixPoolProvider.csproj
src/appsettings.dncenginternal-int.json
src/appsettings.dncenginternal-prod.json
src/appsettings.dncengpublic-int.json
src/appsettings.dncengpublic-prod.json

Current int incarnation works as of 30 mins ago: https://dnceng.visualstudio.com/public/_build/results?buildId=478364&view=logs&j=d6d0747d-862c-5953-c201-f4e1a93f2cef

Rollout new queues

---

src/appsettings.dncenginternal-int.json
src/appsettings.dncenginternal-prod.json
src/appsettings.dncengpublic-int.json
src/appsettings.dncengpublic-prod.json

Part of https://github.com/dotnet/core-eng/issues/8163

Add support for Arcade build queues 

---

src/wwwroot/startupscripts/startagent-linux.sh
src/wwwroot/startupscripts/startagent-mac.sh
src/wwwroot/startupscripts/startagent-win.cmd

Linux:
- Clean workspace in Linux
- Reboot in case of existing workspace 
Windows:
- Reboot after workitem

Handle leaked processes core-eng#9258

---

src/wwwroot/startupscripts/startagent-win.cmd

Call reboot request API before exiting script

---

src/appsettings.dncengpublic-int.json
src/appsettings.dncengpublic-prod.json

Windows 10 Bring-Your-Own-Cloud AMD64 build queue with VS 2019 Preview intended for scouting

New scouting queue BuildPool.Windows.VS2019.Pre.Scouting.Open

---

src/Controllers/PoolProviderController.cs

Noticed it while looking at another PR.

Fix typo in doc comment in PoolProviderController.cs

---

src/appsettings.dncengpublic-int.json
src/appsettings.dncengpublic-prod.json

Checked according to `windows.yaml`

Deleting queues that no longer exist in OSOB

---

src/Controllers/PoolProviderController.cs
src/Models/AgentAcquireItem.cs

This is part of investigation in https://github.com/dotnet/core-eng/issues/11988. The changes will only be applied to staging environment and will be rolled back as soon as we get all the info we need.

Try to get agent/job info in AcquireAgent call and add additional logging

---

src/Controllers/PoolProviderController.cs
src/Models/AgentAcquireItem.cs

This is part of investigation in https://github.com/dotnet/core-eng/issues/11988.
We logged everything we need and can now revert the changes.

Revert "[PoC] Try to get agent/job info in AcquireAgent call and add additional logging"

---

azure-pipelines.yml

https://github.com/dotnet/arcade/issues/7120

m2m renaming

---

src/Controllers/PoolProviderController.cs
src/Models/AgentAcquireItem.cs

This reverts commit 8ed4614b603016ed45a0dc70b7c8223e04aea0e3.
Related issue: https://github.com/dotnet/core-eng/issues/12789

Revert "Temporarily add additional request logging (#470)"

---

src/appsettings.dncengpublic-int.json
src/appsettings.dncengpublic-prod.json

Needed for tomorrow's rollout, to make available for use tomorrow

Adding BuildPool.Windows.Amd64.VS2022.Pre.Open

---

eng/Version.Details.xml
eng/Versions.props
eng/common/build.ps1
eng/common/cross/arm64/tizen-fetch.sh
eng/common/cross/build-android-rootfs.sh
eng/common/cross/build-rootfs.sh
eng/common/dotnet-install.sh
eng/common/generate-locproject.ps1
eng/common/internal-feed-operations.ps1
eng/common/internal-feed-operations.sh
eng/common/msbuild.ps1
eng/common/post-build/sourcelink-validation.ps1
eng/common/post-build/symbols-validation.ps1
eng/common/sdk-task.ps1
eng/common/sdl/execute-all-sdl-tools.ps1
eng/common/sdl/init-sdl.ps1
eng/common/sdl/run-sdl.ps1
eng/common/templates/job/onelocbuild.yml
eng/common/templates/job/source-build.yml
eng/common/templates/job/source-index-stage1.yml
eng/common/templates/post-build/channels/generic-internal-channel.yml
eng/common/templates/post-build/channels/generic-public-channel.yml
eng/common/templates/steps/source-build.yml
eng/common/tools.ps1
eng/common/tools.sh
global.json
src/Controllers/PoolProviderController.cs
src/Models/AgentAcquireItem.cs

Staging build: https://dev.azure.com/dnceng/internal/_build?definitionId=410

[Rollout] Production rollout - June 30th, 2021

---

src/Microsoft.DotNet.HelixPoolProvider.csproj

Ignoring NETSDK1138 warning per conversation in: https://github.com/dotnet/arcade-pool-provider/pull/540

Stop warning NETSDK1138
